const router = require('express').Router();
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const User = require('../models/User');
const BGVRequest = require('../models/BGVRequest');
const CandidateSubmission = require('../models/CandidateSubmission');
const emailService = require('../services/emailService');
const { ROLES, STATUS, STATUS_LABELS } = require('../constants');
const PDFDocument = require('pdfkit');

// ─── GENERATE PDF REPORT ────────────────────────────────────────────────────
router.get('/report/:uid', async (req, res) => {
  try {
    const candidate = await User.findOne({ uid: req.params.uid });
    if (!candidate) return res.status(404).json({ error: "Candidate not found" });

    const bgvRequest = await BGVRequest.findOne({ uid: candidate.bgvRequest });
    if (!bgvRequest) return res.status(404).json({ error: "BGV Request not found" });

    const doc = new PDFDocument({ margin: 50 });
    let filename = `BGV_Report_${candidate.name.replace(/\s+/g, '_')}.pdf`;

    // Set response headers
    res.setHeader('Content-disposition', 'attachment; filename="' + filename + '"');
    res.setHeader('Content-type', 'application/pdf');

    doc.pipe(res);

    // --- Header / Branding ---
    doc.fillColor('#1e293b').fontSize(26).font('Helvetica-Bold').text('BACKGROUND VERIFICATION REPORT', { align: 'center' });
    doc.moveDown();
    doc.fillColor('#3b82f6').fontSize(10).font('Helvetica').text('CONFIDENTIAL - AUTO-GENERATED BY BGV HUB AI', { align: 'center', characterSpacing: 1 });
    doc.moveDown(2);

    // --- Candidate Details Section ---
    doc.rect(50, doc.y, 512, 110).fill('#f8fafc');
    doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('CANDIDATE INFORMATION', 65, doc.y + 10);
    doc.moveDown(0.5);

    doc.fontSize(10).font('Helvetica');
    doc.text(`Full Name: ${candidate.name}`, 65);
    doc.text(`Email Address: ${candidate.email}`, 65);
    doc.text(`Candidate UID: ${candidate.uid}`, 65);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 65);
    doc.moveDown(3);

    // --- Executive Summary ---
    doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('EXECUTIVE SUMMARY', 50);
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica-Oblique').fillColor('#475569')
      .text(bgvRequest.executiveSummary || "No executive summary available yet. Verification may still be in progress.", { lineGap: 4 });
    doc.moveDown(2);

    // --- Verification Details Table ---
    doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('DETAILED VERIFICATION STATUS', 50);
    doc.moveDown();

    const drawRow = (label, status, details) => {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#1e293b').text(label, { continued: true });
      doc.font('Helvetica').fillColor(status.includes('Verified') ? '#10b981' : '#f59e0b').text(`  - ${status}`);
      if (details) {
        doc.fontSize(8).fillColor('#64748b').text(details.replace(/\n/g, ' | '));
      }
      doc.moveDown();
    };

    const ai = bgvRequest.aiVerification || {};
    const docs = ['aadhar', 'pan', 'degree', 'twelfth', 'tenth', 'experience'];

    docs.forEach(d => {
      const res = ai instanceof Map ? ai.get(d) : ai[d];
      const status = res ? (res.verdict === 1 ? "Auto-Verified" : res.verdict === 3 ? "Flagged" : "Needs Review") : "Not Submitted";
      const label = d.charAt(0).toUpperCase() + d.slice(1);
      drawRow(label, status, res?.matchDetails);
    });

    // --- Footer ---
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor('#94a3b8').text(
        `Page ${i + 1} of ${pageCount} | Generated for ${candidate.name} | BGV Hub AI Verification System`,
        50, doc.page.height - 50, { align: 'center' }
      );
    }

    doc.end();

  } catch (err) {
    res.status(500).json({ error: "Failed to generate report: " + err.message });
  }
});

// CREATE CANDIDATE (with reference data and BGVRequest)
router.post('/create-candidate', async (req, res) => {
  try {
    const { name, email, hrId,
      aadharNumber, panNumber,
      tenthPercentage, twelfthPercentage, degreeGPA, degreeName, degreeUniversity,
      previousCompany, previousDesignation, previousDuration,
      hrContactName, hrContactEmail, hrContactPhone, ctc, remarks
    } = req.body;

    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ error: "Email already exists" });

    const bestAgent = await User.findOne({ role: ROLES.AGENT }).sort({ taskCount: 1 });

    const tempPassword = crypto.randomBytes(4).toString('hex');
    const hashedPassword = await bcrypt.hash(tempPassword, 10);

    const newCandidate = new User({
      name,
      email,
      password: hashedPassword,
      role: ROLES.CANDIDATE,
      assignedAgent: bestAgent ? bestAgent.uid : null,
      createdBy: hrId || null,
      isFirstLogin: true
    });

    await newCandidate.save();

    // Create BGVRequest with HR reference data pre-populated
    const hrData = {
      aadharNumber, panNumber,
      tenthPercentage, twelfthPercentage, degreeGPA, degreeName, degreeUniversity,
      previousCompany, previousDesignation, previousDuration,
      hrContactName, hrContactEmail, hrContactPhone, ctc, remarks
    };

    // Remove empty fields
    Object.keys(hrData).forEach(k => { if (!hrData[k]) delete hrData[k]; });

    const newBGVRequest = new BGVRequest({
      candidate: newCandidate.uid,
      hrData: Object.keys(hrData).length > 0 ? hrData : undefined
    });
    await newBGVRequest.save();

    // Link BGVRequest to candidate
    newCandidate.bgvRequest = newBGVRequest.uid;
    await newCandidate.save();

    if (bestAgent) {
      bestAgent.taskCount += 1;
      await bestAgent.save();
    }

    await emailService.sendInvitationEmail(name, email, tempPassword);

    res.json({ message: "Candidate created and assigned to Agent", tempPassword });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Helper to strip _id and __v from objects
const stripIds = (obj) => {
  if (!obj) return obj;
  if (Array.isArray(obj)) return obj.map(stripIds);
  const cleaned = { ...obj };
  delete cleaned._id;
  delete cleaned.__v;
  return cleaned;
};

// GET CANDIDATES (scoped to HR who created them)
router.get('/candidates', async (req, res) => {
  try {
    const { hrId } = req.query;
    const filter = { role: ROLES.CANDIDATE };
    if (hrId) {
      filter.createdBy = hrId;
    }
    const candidates = await User.find(filter).sort({ createdAt: -1 }).lean();

    // Manually resolve assignedAgent uid -> name
    for (let c of candidates) {
      delete c._id;
      delete c.__v;
      if (c.assignedAgent) {
        const agent = await User.findOne({ uid: c.assignedAgent }).select('name uid');
        c.assignedAgentData = agent ? { name: agent.name, uid: agent.uid } : null;
      }
      if (c.bgvRequest) {
        const bgv = await BGVRequest.findOne({ uid: c.bgvRequest }).select('status executiveSummary');
        if (bgv) {
          c.status = bgv.status; // Sync status from BGVRequest
          c.executiveSummary = bgv.executiveSummary;
        }
      }
    }

    res.json(candidates);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET CANDIDATE DETAILED PROGRESS
router.get('/candidate-progress/:uid', async (req, res) => {
  try {
    const candidate = await User.findOne({ uid: req.params.uid }).lean();
    if (!candidate) return res.status(404).json({ error: "Candidate not found" });
    delete candidate._id;
    delete candidate.__v;

    // Resolve agent
    if (candidate.assignedAgent) {
      const agent = await User.findOne({ uid: candidate.assignedAgent }).select('name uid');
      candidate.assignedAgentData = agent ? { name: agent.name, uid: agent.uid } : null;
    }

    // Resolve bgvRequest
    if (candidate.bgvRequest) {
      const bgvData = await BGVRequest.findOne({ uid: candidate.bgvRequest }).lean();
      if (bgvData) { delete bgvData._id; delete bgvData.__v; }
      candidate.bgvRequestData = bgvData;
    }

    let submission = await CandidateSubmission.findOne({ email: candidate.email }).lean();
    if (submission) { delete submission._id; delete submission.__v; }

    res.json({
      ...candidate,
      submission
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// HR SUBMIT REFERENCE DATA FOR CROSS-VERIFICATION
router.post('/submit-hr-data/:candidateUid', async (req, res) => {
  try {
    const { candidateUid } = req.params;
    const { aadharNumber, panNumber, tenthPercentage, twelfthPercentage, degreeGPA, degreeName, degreeUniversity,
      previousCompany, previousDesignation, previousDuration,
      hrContactName, hrContactEmail, hrContactPhone, ctc, remarks } = req.body;

    const candidate = await User.findOne({ uid: candidateUid });
    if (!candidate) return res.status(404).json({ error: "Candidate not found" });

    const bgvRequest = await BGVRequest.findOne({ candidate: candidateUid });
    if (!bgvRequest) return res.status(404).json({ error: "No BGV request found for this candidate" });

    bgvRequest.hrData = {
      aadharNumber, panNumber,
      tenthPercentage, twelfthPercentage, degreeGPA, degreeName, degreeUniversity,
      previousCompany, previousDesignation, previousDuration,
      hrContactName, hrContactEmail, hrContactPhone, ctc, remarks
    };

    await bgvRequest.save();

    res.json({ success: true, message: "HR reference data submitted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});


// ─── BULK CANDIDATE IMPORT ──────────────────────────────────────────────────

const multer = require('multer');
const csv = require('csv-parser');
const fs = require('fs');
const os = require('os');
const path = require('path');

const csvUpload = multer({ dest: os.tmpdir() });

router.post('/bulk-import', csvUpload.single('file'), async (req, res) => {
  try {
    const { hrId } = req.body;
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const results = [];
    const candidates = [];
    const errors = [];

    fs.createReadStream(req.file.path)
      .pipe(csv())
      .on('data', (data) => results.push(data))
      .on('end', async () => {
        // Clean up temp file
        fs.unlinkSync(req.file.path);

        for (const row of results) {
          try {
            const name = row.name || row.Name || row.NAME;
            const email = (row.email || row.Email || row.EMAIL)?.toLowerCase();

            if (!name || !email) {
              errors.push({ row, error: "Missing name or email" });
              continue;
            }

            const existingUser = await User.findOne({ email });
            if (existingUser) {
              errors.push({ row, error: "Email already exists" });
              continue;
            }

            const bestAgent = await User.findOne({ role: ROLES.AGENT }).sort({ taskCount: 1 });
            const tempPassword = crypto.randomBytes(4).toString('hex');
            const hashedPassword = await bcrypt.hash(tempPassword, 10);

            const newCandidate = new User({
              name,
              email,
              password: hashedPassword,
              role: ROLES.CANDIDATE,
              assignedAgent: bestAgent ? bestAgent.uid : null,
              createdBy: hrId || null,
              isFirstLogin: true
            });

            await newCandidate.save();

            // Extract all reference data fields from CSV row
            const hrData = {
              aadharNumber: row.aadharNumber || row.Aadhaar || '',
              panNumber: row.panNumber || row.PAN || '',
              tenthPercentage: row.tenthPercentage || row.Tenth || '',
              twelfthPercentage: row.twelfthPercentage || row.Twelfth || '',
              degreeGPA: row.degreeGPA || row.GPA || '',
              degreeName: row.degreeName || row.Degree || '',
              degreeUniversity: row.degreeUniversity || row.University || '',
              previousCompany: row.previousCompany || row.Company || '',
              previousDesignation: row.previousDesignation || row.Designation || '',
              previousDuration: row.previousDuration || row.Duration || '',
              hrContactName: row.hrContactName || '',
              hrContactEmail: row.hrContactEmail || '',
              hrContactPhone: row.hrContactPhone || '',
              ctc: row.ctc || row.CTC || '',
              remarks: row.remarks || row.Remarks || ''
            };

            const newBGVRequest = new BGVRequest({
              candidate: newCandidate.uid,
              hrData
            });
            await newBGVRequest.save();

            newCandidate.bgvRequest = newBGVRequest.uid;
            await newCandidate.save();

            if (bestAgent) {
              bestAgent.taskCount += 1;
              await bestAgent.save();
            }

            await emailService.sendInvitationEmail(name, email, tempPassword);
            candidates.push({ name, email });
          } catch (err) {
            errors.push({ row, error: err.message });
          }
        }

        res.json({
          message: `Processed ${results.length} rows`,
          importedCount: candidates.length,
          errorCount: errors.length,
          errors
        });
      });
  } catch (err) {
    if (req.file) fs.unlinkSync(req.file.path);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;